name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
        TEST_NAME: ["ScriptedTests", "SbtPre12Tests", "SbtPre1203Tests", "Sbt12Tests"]
        include:
          - OS: windows-latest
            TEST_NAME: ScriptedTests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: 8
        apps: sbt-launcher:1.2.22
    - run: find /usr -name '*libunwind*' -print0 | sudo xargs -0 rm -rf
      shell: bash
      if: runner.os != 'Windows'
    - run: curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      if: runner.os != 'Windows'
      shell: bash
    - run: sbt +publishLocal "testOnly coursier.sbtlauncher.${TEST_NAME}"
      shell: bash
      if: runner.os != 'Windows'
      env:
        TEST_NAME: ${{ matrix.TEST_NAME }}
    - run: BASH="C:\\Program Files\\Git\\bin\\bash.EXE" cs launch sbt-launcher:1.2.22 -- +publishLocal "testOnly coursier.sbtlauncher.${TEST_NAME}"
      shell: bash
      if: runner.os == 'Windows'
      env:
        TEST_NAME: ${{ matrix.TEST_NAME }}

  # job whose name doesn't change when we bump Scala versions, add OSes, …
  # We require this job for auto-merge.
  all-tests:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: true
      shell: bash

  release:
    needs: all-tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: 8
        apps: sbt-launcher:1.2.22
    - run: sbt ci-release
      shell: bash
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  upload-launcher:
    needs: release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: 8
        apps: sbt-launcher:1.2.22
    - run: scripts/upload-launcher/upload-gh-release.sh
      shell: bash
      env:
        REPO: "coursier/sbt-launcher"
        NAME: "csbt"
        CMD: "./scripts/generate-csbt.sh -f --bat=true"

  upload-extras:
    needs: upload-launcher
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: 8
        apps: sbt-launcher:1.2.22
    - run: scripts/update-sbt-extras.sh
      shell: bash
